version: "3"
services:

  config-server:
    environment:
      CONFIG_SERVICE_PASSWORD: pass
    image: letitrock/quizee-config-server
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  discovery-server:
    environment:
      CONFIG_SERVICE_PASSWORD: pass
    image: letitrock/quizee-discovery-server
    restart: always
    depends_on:
      - config-server
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway-service:
    environment:
      CONFIG_SERVICE_PASSWORD: pass
    image: letitrock/quizee-gateway-service
    restart: always
    depends_on:
      - config-server
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-server-mongodb:
    environment:
      MONGODB_PASSWORD: pass
    image: letitrock/quizee-mongodb
    restart: always
    ports:
      - 28000:27017 # TODO REMOVE FROM HERE
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-server:
    environment:
      CONFIG_SERVICE_PASSWORD: pass
      MONGODB_PASSWORD: pass
    image: letitrock/quizee-auth-server
    restart: always
    depends_on:
      - config-server
      - auth-server-mongodb
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service-mongodb:
    environment:
      MONGODB_PASSWORD: pass
    image: letitrock/quizee-mongodb
    restart: always
    ports:
      - 29000:27017 # TODO REMOVE FROM HERE
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: pass
      MONGODB_PASSWORD: pass
    image: letitrock/quizee-account-service
    restart: always
    depends_on:
      - config-server
      - account-service-mongodb
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  quiz-service-mongodb:
    environment:
      MONGODB_PASSWORD: pass
    image: letitrock/quizee-mongodb
    restart: always
    ports:
      - 30000:27017 # TODO REMOVE FROM HERE
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  quiz-service:
    environment:
      CONFIG_SERVICE_PASSWORD: pass
      MONGODB_PASSWORD: pass
    image: letitrock/quizee-quiz-service
    restart: always
    depends_on:
      - config-server
      - quiz-service-mongodb
    logging:
      options:
        max-size: "10m"
        max-file: "10"