# Defined auth server
security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: account-service #${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-server:8000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://auth-server:8000/uaa/users/current

# DB CONFIGURATION
spring:
  data:
    mongodb:
      host: account-service-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: quizee
      port: 27017

# CONTEXT PATH FOR ACCOUNT SERVICE AND PORT
server:
  context-path: /account
  port: 8200