# Defined auth server
security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: account-service #${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-server:8000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

# DB CONFIGURATION
spring:
  data:
    mongodb:
      host: localhost #${MONGO_DB_HOST}
      #username: root
      #password: root #${MONGO_DB_PASSWORD}
      database: quizee
      port: 27017

# CONTEXT PATH FOR ACCOUNT SERVICE AND PORT
server:
  context-path: /account
  port: 8200