# BASE PROPERTIES FOR ALL SERVICES
logging:
  level:
    org.springframework.security: INFO

# BASE OAUTH ENDPOINT FOR CURRENT PRINCIPAL
security:
  # DISABLE BASIC AUTHENTICATION
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIFBTCCAu2gAwIBAgIEayoWJDANBgkqhkiG9w0BAQ0FADAzMREwDwYDVQQKEwhHcmFwZSBVcDELMAkGA1UECxMCSVQxETAPBgNVBAMTCEdyYXBlIFVwMB4XDTE3MTAwNjE3MDQ1NloXDTE4MTAwNjE3MDQ1NlowMzERMA8GA1UEChMIR3JhcGUgVXAxCzAJBgNVBAsTAklUMREwDwYDVQQDEwhHcmFwZSBVcDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAIQk/APeQM4i5mmczQtjagCu050RseH6Vf0b1nHcOJES3ec95UpFjaKO7KW7K++eOR3yFDQgb1LThJt+n03NwI3El3Xy/pin5PPbl2jfSefnO052rdKaakdRMJmUHHzhDur8jqctdtfDZp+hbRF82l97dDXAi5JT8llo1IhK9AYaRJLIyVNsACwEFFMambFPYidrA2z5AJeKISsy0WOgrShPtwSDsC48IHfRQlvVtPPzEgsrwBIqaX8vafKm39ufrcgcIBz7PFNSDGfi4hKL59OPP3U8yB8o5nmJvVwLjy7Ww4f5QC3z5KBxXbhzO0yaZZmbfMl8IaJlff8u+KJPNrWzBgCqbiqqx2p4I2TfEohDKN9jQDN5LboPYa3RRo2XnRzChkFPzSdfJNgleRsxoojZKVzgMb+O/RpS28aAAXl2Ek9fyuRi3jeXNm1XZrrlau4A7k2X0dYP4sk5xHeLKrdVRYe2Dwi9dMPFBUCiv6brHTd0G81+Euqew+g0jj3lohb6F1Jk5ShtTCcfea6i/ditWq1k5KkdCbDzB0BTryO/fMDhdbcVq8tLWOhBzANz/vyg6YiVG50Ln12t+g/Zp84DSAkOQELvETQnLdFs8CQeZ/DwCbjX4UQne8mnz7GsBHALPX/gYyKaAuIFRJlxE3zBGywGRgOdW92Ih+L4cPXfAgMBAAGjITAfMB0GA1UdDgQWBBSAa+5WNd2FVGiOSdkjiZSzb6mqkTANBgkqhkiG9w0BAQ0FAAOCAgEAY/YxmRVv9d9KQ1a06Pe1T9Z45ZDWr57AU7fBcBvT6VHXD0ZeDQvf/QAqQ+rHfVbM6jRm2pNvO0oCJhyaGyE/cb/mpiRht/3Fy4d/T1O/QGkUfdjQ5QfVN/NGbGsV67PIYn5YLot18I5OaS55g8LXgyrqkf7ypVi9xH/cy57bkj9BVC9RQ/P7xglkBzpHs41dl3uM9KwiggfpdwvYGj1ws5EgzD+hl8kVfAwfVGAUA1AXdCRhO2KGsQHf2wihqJBbjf/Go7Ya04X7xifEi066SI6AIlZ16MsUINTumppDXEjBHwzztZGiPbu1hhSzDJnxj36h7mngoAUaByh+xeF8pjFkZOC33rpTBgTGoQOPDwqzjUaBc0jwgC5lp/zerwVtfIYJerg6reJH5r2RddndyPbHx7di2pG+O0xhBRY855f62MqZwy9Ki4ByTM2yiwDmWayTCDXGhSrD2ENvXP+r/LAAV4mQ5cI7zVVTCPcFFUdR02Pv7ylwhTx2RwR/4Pd7NCqKdT12lxZIciFauIM+PTCpUe2iQpX1XewKU9K6/euWO8nCGyIyZke04Hxgy/kdSmx8fhWWx/LI3KQ/Q9QHUulSzIsYbUQvRZbHlD1og/XfDQyL+Ff+rWZP5zDjXsFJcisCxI4CyDkHZ8kbknb/TecFRdCnIaDegJM6O8YZVTU=
          -----END PUBLIC KEY-----
      id: oauth2_id

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/