# BASE PROPERTIES FOR ALL SERVICES
logging:
  level:
    org.springframework.security: INFO

# BASE OAUTH ENDPOINT FOR CURRENT PRINCIPAL
security:
  # DISABLE BASIC AUTHENTICATION
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://auth-server:8000/uaa/users/current
      id: oauth2_id

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

# this ensures that LocalDateTime object is mapped to json like 2017-01-25T21:34:55
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false