# DB CONFIGURATION
spring:
  data:
    mongodb:
      host: localhost #${MONGO_DB_HOST}
      #username: root
      #password: root #${MONGO_DB_PASSWORD}
      database: quizee
      port: 27017

# CONTEXT PATH FOR AUTH SERVER AND PORT
server:
  context-path: /uaa
  port: 8000