# DB CONFIGURATION
spring:
  data:
    mongodb:
      host: auth-server-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: quizee
      port: 27017

# CONTEXT PATH FOR AUTH SERVER AND PORT
server:
  context-path: /uaa
  port: 8000